# Name of workflow
name: linter and tests

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  lint-and-test:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v5
        
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}

      # 1. Устанавливаем зависимости
      - name: Install dependencies
        run: make install
        env:
          CI: true

      # 2. Сначала запускаем линтер на исходном коде
      - name: Run linter
        run: make lint

      # 3. Затем собираем проект
      - name: Build project
        run: make build
        env:
          CI: true

      # 4. И только потом запускаем тесты
      - name: Run tests
        run: make test